### PR TITLE
Sync configuration for all wallets on startup

### PR DESCRIPTION
**Pull request by aymeric-ledger**

### CODE REVIEW

**Comment by YBadiss** [comment]
@luchenyuxx @aymeric-ledger please take a look, this is now tested with the latest version of the libcore

**Comment by aymeric-ledger** [comment]
Looks fine to me, as far as the wallet daemon goes ! I would approve, but it's actually my own PR 😛

**Comment by KhalilBellakrid** [comment]
@YBadiss could we please have some QA before merging this ? Vault should not use it before having this !

**Comment by YBadiss** [comment]
@KhalilBellakrid this is only being merged on develop, once it is done we will deploy it our preprod env for further testing. Only after that will it be deployed on production.

Also note that I tested this fix locally.

**Pull request merged**
